### ISSUE TITLE
Feature: Clarification needed in Translation Guide

### ISSUE THREAD

**Issue by CBID2** [open-sauced/guestbook#219]
### Type of feature

🍕 Feature

### Current behavior

The guestbook’s instructions has not been translated yet, so we needed to make some changes to the first section of the [`translation guide`](https://github.com/open-sauced/guestbook/blob/main/i18n-guidelines.md#-i18n-guide).

### Suggested solution

1. Go to the first section of the [`translation guide`](https://github.com/open-sauced/guestbook/blob/main/i18n-guidelines.md#-i18n-guide).
2. In the part where it says, "At the moment, we have the course in the following languages:", place `(To Be Announced)`next to each bullet point. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
I'm not sure what this issue means or why we need it. Can you clarify, please.

**Comment by CBID2** [comment]
> I'm not sure what this issue means or why we need it. Can you clarify, please.

Hi @BekahHW. I realized that we have not translated been into the languages listed yet, so the changes are needed so that contributors who speak those  languages won’t be confused. Does that make more sense now?

**Comment by BekahHW** [comment]
Ah. Before the first line said translations instead of guestbook. Your edit clarified. 

I actually don't think this is the approach we want to take. The directions to submit are moving to the intro course. 

Also, I wouldn't want to have TBA since we don't have plans to make these translations. If we do want translations, we should have issues for each of them.
